# Ubuntuâ€specific vars
prometheus_version: "2.46.0"
node_exporter_version: "1.6.1"

grafana_repo_url: "https://packages.grafana.com/oss/deb"
grafana_signing_key_url: "https://packages.grafana.com/gpg.key"

jenkins_repo_key_url: "https://pkg.jenkins.io/debian/jenkins.io.key"
jenkins_repo: "deb https://pkg.jenkins.io/debian-stable binary/"
